version: "3.7"

services:

  nginx:
    build:
      context: ./Nginx
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
    restart: always

  dotnet:
    depends_on:
      - nginx
    build:
      context: .
      dockerfile: Dotnet.Dockerfile
    expose:
      - "5000"
    restart: always
